### ISSUE TITLE
zoxide not found

### ISSUE THREAD

**Issue by szinn** [MLFlexer/smart_workspace_switcher.wezterm#10]
I've run into an issue using alacritty with tmux, and use Josh's session manager (must have!).

WezTerm appears to fix my issue and so glad to discover this plugin!

Anyways, it didn't work for me so I debugged a bit by pasting the plugin code into my wezterm.lua.

It turns out that for my system (I use nix as my package manager) zoxide isn't on the system path and I had to change the script to fully qualify zoxide's location.

Is there a way to allow the zoxide path to be supplied to the script somehow?

I might be able to hack it on my side as well

**Comment by MLFlexer** [comment]
I'm on NixOS and do not have Zoxide installed on a system level, only on a userlevel, and i don't have this problem. So you might be able to fix your problem with Josh's session manager if you would rather use that.

However i am sure it would be possible to add it as a parameter to the [apply_to_config](https://github.com/MLFlexer/smart_workspace_switcher.wezterm/blob/3e260eaf32f8bb9de259e529817614243cf35f98/plugin/init.lua#L74) function.

I will try and look into it later today, but feel free to create a PR if you want it fixed immediately :smile:

**Comment by MLFlexer** [comment]
Fixed by #12

**Comment by MLFlexer** [comment]
@szinn FYI, I have made some changes to the configuration with the merge of #15 , if you are updaing the plugin to get the changes which fixes this, then you should be aware that you might need to change your config as per the new README
