### ISSUE TITLE
Right status title isn't updated when workspace is closed

### ISSUE THREAD

**Issue by szinn** [MLFlexer/smart_workspace_switcher.wezterm#11]
Scenario is that there are multiple workspaces that have been created using the plugin. On the active one, the right title is correctly displayed. However, if that workspace is closed, a new workspace gets focus, but the right title stays unchanged rather than being replaced with the title of the new workspace.

Perhaps the setting of the title should be done when the pane gets focus and receives an on focus change event. There would likely need to be some state attached to the workspace to indicate that it should trigger a title update.

When I get a moment to play around with it and learn a little lua, I'll give some ideas a go.

**Comment by MLFlexer** [comment]
I think you are right in your assessment of the problem and that the title should be set as a part of a focus event like [this](https://wezfurlong.org/wezterm/config/lua/window-events/window-focus-changed.html).

I would have to think a little about this, which i probably wont have time to do before the weekend. If you have any solution to this then a PR is always welcome! :smile:

**Comment by szinn** [comment]
I think the right thing to do on this one is to not set the right status title at all in the plugin - let the user configure the display themselves - leave the plugin purely to pick and create / switch to the workspace.

**Comment by szinn** [comment]
For example, I've added the following to my wezterm.lua and it solves the problem nicely

```
local function basename(s)
    return string.gsub(s, "(.*[/\\])(.*)", "%2")
end

local function update_right_status(window)
    title = basename(window:active_workspace())
    if window:is_focused() then
        window:set_right_status(wezterm.format {
            { Foreground = { Color = "#F8F8F2" } },
            { Text = title .. "  " }
        })
    end
end

wezterm.on('window-focus-changed', function(window, pane)
    update_right_status(window)
end)

wezterm.on('update-right-status', function(window, pane)
    update_right_status(window)
end)
```

**Comment by MLFlexer** [comment]
> I think the right thing to do on this one is to not set the right status title at all in the plugin - let the user configure the display themselves - leave the plugin purely to pick and create / switch to the workspace.

I agree, I think the best thing is to expose access to the workspace name via. a function, and then let the user decide how to use it. Maybe provide an easy way to set it up via the README

**Comment by szinn** [comment]
The workspace name is already available via window:

**Comment by MLFlexer** [comment]
I see, gonna remove it from the plugin then
