### ISSUE TITLE
Zoxide not found in Wezterm run from /Applications/ in MacOS

### ISSUE THREAD

**Issue by theherk** [MLFlexer/smart_workspace_switcher.wezterm#20]
Based on the issue detailed [here in the FAQ](https://wezfurlong.org/wezterm/faq.html?h=macos#im-on-macos-and-wezterm-cannot-find-things-in-my-path) the root Wezterm instance run from the Applications launcher on MacOS has only the sparse `PATH` from /etc/paths. This is fine for running wezterm, but insufficient for really running much else, including zoxide.

The simplest way to get around this, in my view, is to simple run against a users shell. Pull request forthcoming.

**Comment by MLFlexer** [comment]
Awesome, that you noticed this bug!
