### ISSUE TITLE
CTRL-j/k do not work

### ISSUE THREAD

**Issue by jeffp123** [MLFlexer/smart_workspace_switcher.wezterm#41]
I can use CTRL-p/n, as well the arrow keys, to navigate, but not CTRL-j/k

Interestingly, I _can_ use ctrl-j/k with the example here: https://wezfurlong.org/wezterm/config/lua/keyassignment/InputSelector.html?h=input+selector#example-of-choosing-some-canned-text-to-enter-into-the-terminal

**Comment by MLFlexer** [comment]
Very strange, it seems like I am able to use CTRL-p/n and CTRL-j, but not CTRL-k.

I also don't see why it should be different from the input selector you linked.

**Comment by jeffp123** [comment]
Aha! If I turn off the github smart-splits plugin, ctrl-j/k work!

Strangely, in the example with the input selector, it _still worked_, which makes me think that it is dependent on the order of how things are loaded. Perhaps, this and that both being _plugins_ is related?

I can to look into it more, but the culprit is, as you noted, a conflicting keybinding.

**Comment by jeffp123** [comment]
My mistake. Ctrl-k/j _is_ being canceled by `smart-splits` key bindings even in the small example.

So, it is consistent and not a bug with smart-workspace-switcher. Closing.

**Comment by jeffp123** [comment]
The following work-around seems to fix issues related to key-bindings interfering with the input selector motions, at least for ctrl-j/k:

```lua
wezterm.on("smart_workspace_switcher.workspace_switcher.start", function(window, pane)
	local overrides = window:get_config_overrides() or {}
	local keys_override = {}
	for _, l in ipairs(config.keys) do
		if l.mods ~= "CTRL" or l.key ~= "j" and l.key ~= "k" then
			table.insert(keys_override, l)
		end
	end

	overrides.keys = keys_override
	window:set_config_overrides(overrides)
end)

wezterm.on("smart_workspace_switcher.workspace_switcher.selected", function(window, path, label)
	local overrides = window:get_config_overrides() or {}
	overrides.keys = nil
	window:set_config_overrides(overrides)
end)

wezterm.on("smart_workspace_switcher.workspace_switcher.canceled", function(window, path, label)
	local overrides = window:get_config_overrides() or {}
	overrides.keys = nil
	window:set_config_overrides(overrides)
end)
```

I'm not sure if there is a more general way to hook into the `InputSelector` directly, but the events provided by `smart_workspace_switcher` do the trick nicely.

**Comment by MLFlexer** [comment]
Awesome that you figured it out and are sharing the solution, thanks! 😄
