### ISSUE TITLE
Add command to switch to last workspace

### ISSUE THREAD

**Issue by Bacbia3696** [MLFlexer/smart_workspace_switcher.wezterm#42]
Thank you for providing such fantastic plugin! With it, I can fully replace tmux with Wezterm. However, I've noticed that switching to the last workspace is a common action, and it's not straightforward to accomplish in Wezterm. It would be wonderful if your plugins could support this feature.
Thank you so much!

**Comment by MLFlexer** [comment]
Thanks for the kind words 😄 

Would you like to switch to the latest workspace after having opened wezterm from a closed state or if you have workspace A and B open, to quickly switch between A and B?

**Comment by Bacbia3696** [comment]
I mean quickly switching between workspaces A and B.

The workflow involves primarily working in the main workspace, then navigating to other workspaces using your plugins, and finally returning to the main workspace. Currently, I have to open a list and select my main workspace each time.

I am considering something like this: https://github.com/wez/wezterm/discussions/5833. When I use Tmux, there is a command called last-session.

If you find my suggestion unsuitable, I would appreciate any guidance on an easier way to achieve this.
Thank you a lot!

**Comment by MLFlexer** [comment]
I really like the idea, I have added a keybind with #43. 
If you have any other suggestions then I would love to hear them :smile:
