### ISSUE TITLE
add rename and delete options

### ISSUE THREAD

**Issue by honeyspoon** [MLFlexer/smart_workspace_switcher.wezterm#44]
not sure how flexible the fuzzy finder is so maybe we won't be able to do this

tmux's session switcher allows for renaming deleting and renaming sessions

**Comment by honeyspoon** [comment]
atm I'm using this and it's working well
```
{
key = "$",
mods = "LEADER",
action = wezterm.action.PromptInputLine({
	description = "Enter new name for workspace",
	action = wezterm.action_callback(function(window, pane, line)
		if line then
			wezterm.mux.rename_workspace(wezterm.mux.get_active_workspace(), line)
		end
	end),
}),
},
```

**Comment by MLFlexer** [comment]
I like the idea, but I don't think this is currently possible to do in the same fuzzy finder, as it is only possible to bind a single action to be activated when picking an item.

You might be able to make a seperate fuzzy finder to delete 1 workspace at a time, and another to pick a single workspace and then prompt for input, like in your example, but I don't think it is possible to use the same fuzzy finder, but different keybinds for all actions.

**Comment by honeyspoon** [comment]
makes sense
thanks
