### ISSUE TITLE
Creation of new workspace

### ISSUE THREAD

**Issue by nlvratna** [MLFlexer/smart_workspace_switcher.wezterm#45]
Can anyone tell new how a new workspace is created 
I am not able to do that

**Comment by MLFlexer** [comment]
If you have the following config:
```lua
local workspace_switcher = wezterm.plugin.require("https://github.com/MLFlexer/smart_workspace_switcher.wezterm")

config.leader = { key = "Space", mods = "CTRL|SHIFT", timeout_milliseconds = 1000 }
config.keys = {
  -- ...
  -- your other keybindings
  {
    key = "s",
    mods = "LEADER",
    action = workspace_switcher.switch_workspace(),
  },
  {
    key = "S",
    mods = "LEADER",
    action = workspace_switcher.switch_to_prev_workspace(),
  }
}
-- ...
```

Then you can press `ctrl+shift+space` and then press `s` to open the fuzzy finder

**Comment by nlvratna** [comment]
```
local workspace_switcher = wezterm.plugin.require("https://github.com/MLFlexer/smart_workspace_switcher.wezterm")
workspace_switcher.apply_to_config(config)
config.leader = { key = "a", mods = "CTRL", timeout_milliseconds = 2000 }

	{
		key = "t", 
		mods = "LEADER",
		action = workspace_switcher.switch_workspace(),
	},
```
when I use <leader>t  it shows only default workspace
![image](https://github.com/user-attachments/assets/9504d4a1-7514-4e58-9b12-5ae0caa4a245)

I am using Ubuntu wsl
```
if is_windows then
	config.wsl_domains = {
		{
			name = "WSL:Ubuntu-24.04",
			distribution = "Ubuntu-24.04",
			default_cwd = "~",
		},
	}
	config.default_domain = "WSL:Ubuntu-24.04"
end
```

**Comment by MLFlexer** [comment]
I think using WSL is the problem then, it will use the zoxide binary from the system which wezterm is being launched, if you are launching it on windows to connect to wsl via a domain, then this wont work unfortunetly.

It might work if you move your config into wsl and then launch wezterm from there with wsl2 as seen [here](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps).

**Comment by nlvratna** [comment]
It might work but Unfortunately I don't think I can try it 

Thanks man

**Comment by adam-beck** [comment]
**Nevermind**
I am using mise to install tools (including zoxide). After providing a custom path it seems to be working.

I don't have a lot of experience in this area, but I will mention that the same thing is happening for me on PopOS inside of a VMWare Virtual Machine.

The same configuration I have works fine on MacOS.

> ERROR logging > lua: Child process 'zoxide query -l ' failed with stderr: 'zsh:1: command not found: zoxide

Running this same command from my terminal is fine, though.

Wonder if it's related to https://github.com/MLFlexer/smart_workspace_switcher.wezterm/issues/40

**Comment by mwojick** [comment]
I was able to get it to work by changing process_args like so:

```lua
if is_windows then
	process_args = { "wsl", "-e", "sh", "-c", cmd }
end
```

and change the path to where it's installed on wsl. In my case:

```lua
workspace_switcher.zoxide_path = "~/.nix-profile/bin/zoxide"
```
