### ISSUE TITLE
Can't Install: unsupported URL protocol; class=Net (12)

### ISSUE THREAD

**Issue by joshmedeski** [MLFlexer/smart_workspace_switcher.wezterm#6]
Hey @MLFlexer, cool plugin! 😉

I followed the instructions and am getting this error:

> unsupported URL protocol; class=Net (12)

```
local workspace_switcher = wezterm.plugin.require("https://github.com/MLFlexer/smart_workspace_switcher.wezterm")
workspace_switcher.apply_to_config(config, "b", "ALT", function(label)
	return wezterm.format({
		-- { Attribute = { Italic = true } },
		-- { Foreground = { Color = "green" } },
		-- { Background = { Color = "black" } },
		{ Text = "󱂬: " .. label },
	})
end)
```

Any ideas how to resolve this?

**Comment by joshmedeski** [comment]
Looking into it more it may have something to do with my git setup using SSH instead of HTTPS, but still unsure how to fix it.

**Comment by MLFlexer** [comment]
Hey man, awesome that you are trying out the plugin! 😄 

What version do you have of wezterm? and have you checked the output of the debug overlay (default keybind is `CTRL+SHIFT+L`)?

I use SSH with my git aswell, so I don't know if that is the case

**Comment by joshmedeski** [comment]
I had to disable this feature in my global git config:
```
[url "git@github.com:"]
	insteadOf = https://github.com/
```

**Comment by MLFlexer** [comment]
Great, updating the title if anyone else has this problem
