### ISSUE TITLE
Plugin initialization; settings and bindings

### ISSUE THREAD

**Issue by danjessen** [MLFlexer/smart_workspace_switcher.wezterm#9]
First of:
Hej Malthe fedt plugin.

Second:
I was wondering if the initialization and setup could be optimized.

The apply_to_config is a great way to add settings

So colors, translations, zoxide vs sessions vs path reference

The keybinds could maybe be handled as an event ?

**Comment by MLFlexer** [comment]
Hej, tak! 😄 

It is already possible to add some configuration like formatting the workspaces.
However if you want more customization, then it would be cool if you can specify what you are looking for such that I can try and make it happen (or if you want to do it yourself, a PR is welcome)

If you could elaborate a bit on what specifically you are looking for with: "So colors, translations, zoxide vs sessions vs path reference", then that would be awesome! 😃

**Comment by danjessen** [comment]
We can maybe talk about it. I'm on Josh's discord. It's a nice little community for stuff like this.

**Comment by MLFlexer** [comment]
Sure, I have joined it now

**Comment by MLFlexer** [comment]
Summary of suggestions:

- prefix workspace names with the name of the git root
This will probably not be included in this plugin, as the right-status-update have been removed from this plugin, and added as a feature a single user can add, see #11.
- setting to show either workspaces or zoxide paths first
see #18 
- Addition of callbacks with change of workspace session
see #19
- Setting a color per workspace
This could be implemented by the user via. the addition of callbacks with change of workspace session. 

Closing this issue, and adding individual issues.
